'use strict';
const animals=[['owl','fly','🦉'],['rabbit','hop','🐰'],['frog','jump','🐸'],['dog','run','🐶'],['eagle','soar','🦅'],['duck','walk','🦆'],['fish','swim','🐟'],['iguana','climb','🦎']].map(([animal,action,emoji],id)=>({animal,action,emoji,id}));
const $=q=>document.querySelector(q),ctx=$('#world').getContext('2d'),keys=new Set();let p={runs:0,seen:[],weak:{},best:0};try{const v=JSON.parse(localStorage.getItem('wild-switch-v1'));if(v&&Array.isArray(v.seen)&&v.weak&&typeof v.weak==='object')p={runs:Number(v.runs)||0,seen:v.seen.filter(i=>Number.isInteger(i)&&i>=0&&i<8),weak:v.weak,best:Number(v.best)||0}}catch{}
// 載入去背角色圖片資源
const spriteImages = {};
['owl','rabbit','frog','dog','eagle','duck','fish','iguana','default'].forEach(name => {
  const img = new Image();
  img.src = `sprites/${name}.png`;
  spriteImages[name] = img;
});
let s={mode:'home',route:[],at:0,x:90,y:418,vy:0,facing:1,selected:-1,choices:[],score:0,combo:0,phase:'approach',time:0,coins:[],errors:0,reviews:0},muted=false,audio=null,seed=17,last=0,manual=false;
function save(){try{localStorage.setItem('wild-switch-v1',JSON.stringify(p))}catch{}}function rand(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rand()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function target(){return animals[s.route[s.at]?.id??0]}function status(t){$('#status').textContent=t}
function say(word){if(audio)audio.pause();if(muted)return;audio=new Audio(`V1_flashcards_audios/V1_${word}.mp3`);audio.play().catch(()=>{if(s.mode==='play')status(`聲音無法播放，文字提示：${target().action}。`)})}
function hud(){$('#round').textContent=s.mode==='home'?'準備探險':`第 ${Math.min(s.at+1,s.route.length)} / ${s.route.length} 站${s.route[s.at]?.retry?' · 再挑戰':''}`;$('#score').textContent=`★ ${s.score}`;$('#combo').textContent=s.combo?`✦ 連續 ${s.combo} 次技能成功`:'跳起來收集星星';$('#collection').textContent=`圖鑑 ${p.seen.length} / 8 · 最佳 ★ ${p.best}`}
function modal(t){$('#overlay').hidden=false;$('#overlay').innerHTML=`<div class="modal">${t}</div>`}function home(){s.mode='home';keys.clear();if(audio)audio.pause();modal('<h2>把英文變成超能力</h2><p>左右移動，跳起收集星星。<br>走到地形前，選動物，按 <b>E 施展技能</b> 過關！</p><select id="difficulty" aria-label="難度"><option value="read">探索模式 · 英文＋聲音</option><option value="listen">聽力模式 · 先聽，再變身</option></select><br><button id="start">開始冒險 →</button><p>每趟 8 站 · 路線重新排列 · 錯誤技能稍後再練</p>');$('#start').onclick=start;const diff=$('#difficulty');if(diff)diff.onchange=()=>cards(true);cards(true);hud();draw()}
function start(){s.listening=$('#difficulty').value==='listen';seed=17+(++p.runs)*319;save();let ids=shuffle(animals.map(a=>a.id));ids.sort((a,b)=>(Number(p.weak[b])||0)-(Number(p.weak[a])||0));Object.assign(s,{mode:'play',route:ids.map(id=>({id,retry:false})),at:0,score:0,combo:0,errors:0,reviews:0,time:0});$('#overlay').hidden=true;$('#pause').textContent='Ⅱ 暫停';segment();$('#world').focus()}
function segment(){Object.assign(s,{x:90,y:418,vy:0,phase:'approach',failed:false,powerTime:0,selected:-1});keys.clear();s.coins=[{x:175,y:400},{x:255,y:342},{x:350,y:385},{x:830,y:390},{x:940,y:340},{x:1070,y:390}];s.choices=shuffle([target().id,...shuffle(animals.filter(a=>a.id!==target().id).map(a=>a.id)).slice(0,3)]);cards();status('往右探索，跳起收集星星！前方地形需要動物技能。');hud();draw()}
function cards(preview=false){
  const isListen = s.mode==='play' ? s.listening : ($('#difficulty')?.value==='listen');
  $('#cards').innerHTML=(preview?[3,2,6,0]:s.choices).map((id,n)=>{
    const a=animals[id];
    // 聽力模式：先聽動作，再從卡片中挑選動作 (b標籤顯示 action)
    // 探索模式：看板已顯示動作單字，卡片顯示動物名稱 (b標籤顯示 animal)，避免形成答案直接對照
    const title = isListen ? a.action : a.animal;
    const sub = isListen ? `${n+1} · ${a.animal}` : `${n+1}`;
    return `<button class="card ${s.selected===id?'selected':''}" data-id="${id}" aria-pressed="${s.selected===id}"><img src="V1_flashcards_images/V1_${a.animal}.webp" alt="${a.emoji}"><b>${title}</b><small>${sub}</small></button>`;
  }).join('');
  $('#cards').querySelectorAll('button').forEach(b=>b.onclick=()=>select(Number(b.dataset.id)));
  $('#cards').querySelectorAll('img').forEach(i=>i.onerror=()=>i.replaceWith(document.createTextNode(i.alt)));
}
function select(id){if(s.mode!=='play'||s.phase==='power')return;s.selected=id;cards();say(animals[id].action);status(`${animals[id].emoji} ${animals[id].animal} 準備好了！走到地形前，按 E。`)}function jump(){if(s.mode==='play'&&s.phase!=='power'&&s.y>=417)s.vy=-510}
function power(){if(s.mode!=='play'||s.phase==='power')return;if(s.phase!=='gate'){status('先往右走到地形標誌前。');return}if(s.selected<0){status('先選下方的動物技能，再按 E。');return}if(s.selected!==target().id){s.errors++;s.failed=true;s.combo=0;p.weak[target().id]=(Number(p.weak[target().id])||0)+1;save();status(`試試 ${target().emoji} ${target().animal} 的 ${target().action}，再按 E！`);say(target().action);hud();return}s.phase='power';s.powerTime=0;s.combo++;s.score+=10;status(`${['owl','eagle','iguana'].includes(target().animal)?'An':'A'} ${target().animal} can ${target().action}!`);say(target().action);if(!p.seen.includes(target().id))p.seen.push(target().id);if(!s.failed)p.weak[target().id]=Math.max(0,(Number(p.weak[target().id])||0)-1);if(s.failed&&!s.route[s.at].retry){s.route.splice(Math.min(s.at+4,s.route.length),0,{id:target().id,retry:true});s.reviews++}save();hud()}
function finish(){s.mode='done';keys.clear();p.best=Math.max(p.best,s.score);save();hud();modal(`<h2>你點亮了整座公園！</h2><p>收集 <b>★ ${s.score}</b> · 完成 ${s.route.length} 個地形<br>回頭練習 ${s.reviews} 次 · 圖鑑 ${p.seen.length} / 8</p><p>下次換一條路，再試試聽力模式！</p><button id="again">回營地 / 再玩一次 ↻</button>`);$('#again').onclick=home}
function pause(){if(s.mode==='play'){s.mode='paused';keys.clear();if(audio)audio.pause();modal('<h2>營火休息時間</h2><p>準備好了，接著冒險。</p><button id="resume">繼續冒險 →</button>');$('#resume').onclick=pause;$('#pause').textContent='▶ 繼續'}else if(s.mode==='paused'){s.mode='play';$('#overlay').hidden=true;$('#pause').textContent='Ⅱ 暫停';$('#world').focus()}}
function tick(dt){if(s.mode!=='play')return;s.time+=dt;if(s.phase==='power'){s.powerTime+=dt;const t=Math.min(s.powerTime/1.6,1),act=target().action;s.x=480+300*t;s.facing=1;s.y=act==='swim'?435+Math.sin(t*10)*8:['walk','run'].includes(act)?418:418-Math.sin(t*Math.PI)*(act==='hop'?65:act==='climb'?175:130);if(t===1){s.phase='exit';s.y=418;s.vy=0;status('成功！收集剩下的星星，往右走到下一站 →')}}else{const dx=((keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0));if(dx!==0)s.facing=dx>0?1:-1;s.x+=dx*260*dt;s.x=Math.max(32,s.x);s.vy+=1250*dt;s.y=Math.min(418,s.y+s.vy*dt);if(s.y===418)s.vy=0;if(['approach','gate'].includes(s.phase)&&s.x>=480){s.x=480;if(s.phase==='approach'){s.phase='gate';status(s.listening?'聽提示，選技能卡，再按 E！':`這一站需要 ${target().action}！選動物，再按 E。`);say(target().action)}}if(s.phase==='exit'&&s.x>1150){s.at++;if(s.at>=s.route.length)finish();else segment()}}for(const c of s.coins){if(!c.got&&Math.hypot(s.x-c.x,s.y-25-c.y)<43){c.got=true;s.score++;hud()}}}
function oval(x,y,rx,ry,c){ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,7);ctx.fill()}
// 繪製去背角色圖案（含左右翻轉與縮放）
function drawCharacter(x,y){
  const imgName = s.selected>=0 ? animals[s.selected].animal : 'default';
  const img = spriteImages[imgName];
  if(img && img.complete && img.naturalWidth > 0){
    const h = 64; // 角色高度（微調最佳視覺尺寸）
    const w = (img.naturalWidth / img.naturalHeight) * h;
    ctx.save();
    ctx.translate(x, y - h/2 + 20);
    if(s.facing < 0) ctx.scale(-1, 1);
    ctx.drawImage(img, -w/2, -h/2, w, h);
    ctx.restore();
  } else {
    // 降級備用 Emoji
    ctx.fillStyle='#ffffff';
    ctx.font='51px "Segoe UI Emoji",sans-serif';
    ctx.fillText(s.selected>=0?animals[s.selected].emoji:'🦊',x,y+10);
  }
}
function draw(){ctx.fillStyle='#cce4d9';ctx.fillRect(0,0,1200,540);oval(1000,90,52,52,'#ffe9a7');for(const x of [170,560,850]){oval(x,95,64,20,'#edf4e5');oval(x+30,85,32,24,'#edf4e5')}for(const [x,y,r] of [[100,340,230],[400,350,210],[840,330,290],[1150,300,200]])oval(x,y,r,180,'#a9c9ad');for(const x of [30,320,910,1130]){ctx.fillStyle='#678e68';ctx.fillRect(x,245,15,185);oval(x+5,225,60,82,'#699878');oval(x-15,210,38,54,'#7fab83')}ctx.fillStyle='#486d50';ctx.fillRect(0,440,1200,100);ctx.fillStyle='#86a967';ctx.fillRect(0,440,1200,12);const act=target().action;if(['fly','soar','swim'].includes(act)){ctx.fillStyle='#75b8ba';ctx.fillRect(540,440,190,100);ctx.fillStyle='#bfe4d6';for(let y=460;y<540;y+=25)ctx.fillRect(550,y,170,3)}else if(act==='climb'){ctx.fillStyle='#956f49';ctx.fillRect(600,245,55,195);oval(628,220,90,65,'#528568')}else if(act==='walk'){ctx.fillStyle='#755d43';ctx.fillRect(540,445,200,80);ctx.fillStyle='#d5af70';ctx.fillRect(530,425,220,14)}else if(act==='jump'){oval(620,443,90,22,'#77b9bb');oval(630,390,43,13,'#559754')}else if(act==='hop')oval(630,430,43,27,'#8a9981');else{ctx.fillStyle='#ffcc75';for(let x=550;x<735;x+=45){ctx.beginPath();ctx.moveTo(x,400);ctx.lineTo(x+22,413);ctx.lineTo(x,426);ctx.fill()}}ctx.textAlign='center';ctx.fillStyle='#244f43';ctx.fillRect(420,262,8,178);ctx.fillStyle='#fff0bd';ctx.beginPath();ctx.roundRect(362,252,144,65,12);ctx.fill();ctx.fillStyle='#3e5b40';ctx.font='bold 22px sans-serif';ctx.fillText(s.listening?'♫ LISTEN':act,434,291);ctx.fillStyle='#fff2bf';ctx.font='28px sans-serif';for(const c of s.coins)if(!c.got)ctx.fillText('★',c.x,c.y);ctx.fillStyle='#fff0b7';ctx.fillRect(1145,325,5,115);ctx.fillStyle='#e88d50';ctx.beginPath();ctx.moveTo(1150,325);ctx.lineTo(1190,345);ctx.lineTo(1150,366);ctx.fill();oval(s.x,444,25,7,'#284d4655');drawCharacter(s.x,s.y);if(s.phase==='power'){ctx.font='24px sans-serif';ctx.fillText('✦',s.x-40,s.y-12)}if(s.mode==='play'&&s.phase==='gate'){ctx.fillStyle='#244d43';ctx.font='bold 17px sans-serif';ctx.fillText('選技能 → E',s.x,225)}ctx.textAlign='left';ctx.fillStyle='#dce8ca';ctx.font='12px sans-serif';ctx.fillText('← → MOVE    SPACE JUMP    1–4 SWITCH    E POWER',25,520)}
function frame(ts){if(!manual)tick(Math.min((ts-last)/1000||0,0.04));last=ts;draw();requestAnimationFrame(frame)}document.addEventListener('keydown',e=>{if(e.target.matches('select')||e.target.matches('button')&&['Enter',' '].includes(e.key))return;if(['ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.repeat&&[' ','e','E','p','Escape'].includes(e.key))return;keys.add(e.key);if(e.key===' ')jump();if(e.key.toLowerCase()==='e')power();if(e.key.toLowerCase()==='p'||e.key==='Escape')pause();if(['1','2','3','4'].includes(e.key)&&s.choices[Number(e.key)-1]!==undefined)select(s.choices[Number(e.key)-1]);if(e.key.toLowerCase()==='f'&&document.fullscreenEnabled){if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else $('.stage').requestFullscreen().catch(()=>{})}});document.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>{keys.clear();if(s.mode==='play')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&s.mode==='play')pause()});document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key)};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>keys.delete(b.dataset.key)});$('#jump').onclick=jump;$('#power').onclick=power;$('#pause').onclick=pause;$('#listen').onclick=()=>{if(s.mode==='play')say(target().action)};$('#mute').onclick=()=>{muted=!muted;if(audio&&muted)audio.pause();$('#mute').textContent=muted?'♫ 聲音關':'♫ 聲音開';$('#mute').setAttribute('aria-pressed',String(muted))};window.render_game_to_text=()=>JSON.stringify({mode:s.mode,phase:s.phase,round:s.at+1,total:s.route.length,player:{x:Math.round(s.x),y:Math.round(s.y)},prompt:s.listening?'audio':target().action,target:target().animal,options:s.choices.map(i=>animals[i].animal),selected:animals[s.selected]?.animal,stars:s.score,errors:s.errors,reviews:s.reviews,combo:s.combo,collected:p.seen.length,status:$('#status').textContent,coordinates:'1200x540; top-left origin; x right/y down; ground y418; gate x480; exit x>1150'});window.advanceTime=ms=>{manual=true;for(let t=0;t<ms;t+=1000/60)tick(Math.min(1000/60,ms-t)/1000);draw()};home();requestAnimationFrame(frame);
